name: Rainbucket CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - uses: thaind0/envfile@v1
      with:
        secrets: ${{ toJSON(secrets) }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        mv .env ./backend
        cd frontend
        npm i
        npm run build
        cp -r dist ../backend
        cd ../backend
        npm i
        cd ..
        pm2 stop 0
        pm2 start 0
        pm2 save
